### ISSUE TITLE
Reduce expected types in LabProtocol?

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/isa-ro-crate-profile#11]
![image](https://github.com/nfdi4plants/isa-ro-crate-profile/assets/17880410/89dc7e08-908a-4ba7-a17a-1c59162a8f87)

Maybe add some more restrictions? Else, this could lead to problems with compatability between parsers.

**Comment by floWetzels** [comment]
Which types should be removed? To me, only `BioChemEntity` and `SoftwareApplication` make sense, maybe `URL` as well. We shouldn't remove `PropertyValue`, since we wanted to use that for a very specific reason. It was our proposal to add them to the bioschemas type afterall. I also think we should keep `DefinedTerm` and `Text` for ease of use.

Any ideas on that, @HLWeil @stuzart @Freymaurer ?

**Comment by floWetzels** [comment]
@HLWeil @stuzart  What do you say?

**Comment by floWetzels** [comment]
This discussion seems to go nowhere, I will close this for now.
